apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: albala-ml-tls
spec:
  secretName: albala-ml
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: albala.ml
  dnsNames:
    - albala.ml
    - www.albala.ml
